Sprint 05
esplusnin/MovieQuiz-ios pull request #6
Opened 2023-01-15 14:53 UTC by esplusnin

Задание сделано согласно техническому заданию

2023-01-15 20:33 UTC, IBDesignable requested changes

2023-01-15 20:33 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            let finalWindow = AlertModel(title: "Этот раунд окончен!",
Можно использовать [многострочный вариант строки](https://www.swiftbysundell.com/tips/multiline-string-literal-tips-and-tricks/), чтобы строчка кода умещалась в столбец 120-180 символов:

```
let textDog = """
╥━━━━━━━━╭━━╮━━┳
╢╭╮╭━━━━━┫┃▋▋━▅┣
╢┃╰┫┈┈┈┈┈┃┃┈┈╰┫┣
╢╰━┫┈┈┈┈┈╰╯╰┳━╯┣
╢┊┊┃┏┳┳━━┓┏┳┫┊┊┣
╨━━┗┛┗┛━━┗┛┗┛━━┻
"""
```

2023-01-15 20:33 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            let bestGameDate = statisticService.bestGame.date.dateTimeString
кажется правильнее сначала сохранить данные, затем собирать строки.

2023-01-15 20:33 UTC, IBDesignable commented on MovieQuiz/Services/StatisticService.swift
> +        gamesCount += 1
эту строчку бы перенести выше, чтобы корректно считалось выше

2023-01-16 09:46 UTC, esplusnin commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            let bestGameDate = statisticService.bestGame.date.dateTimeString
Александра, вы лучший ревьюер! =)

2023-01-16 18:52 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            let bestGameDate = statisticService.bestGame.date.dateTimeString
Спасибо, очень приятно!)

2023-01-16 18:53 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            Ваш результат: \(correctAnswers)/\(questionsAmount)\n Количество сыгранных квизов: \(totalGamesCount)\n Рекорд: \(currentCorrectRecord)/\(currentTotalRecord) (\(bestGameDate) \n Средняя т
теперь можно вместо \n прямо начинать с новой строки

2023-01-17 08:35 UTC, merged